import {
  CODBSharePoint,
  addColumn,
  addFormatting,
  addGraphPermission,
  addList,
  addPage,
  addProvisioning,
  addTheme,
  addWebPart,
  createIR,
  validateSPPKGPackage
} from '../src/index.js';
import { strFromU8, unzipSync } from 'fflate';

const sdk = new CODBSharePoint();

describe('CODBSharePoint - feature-rich battle test package', () => {
  it('builds a multi-web-part operational portal with Graph, Sass, localization, and provisioning', async () => {
    const ir = createIR({
      name: 'BattlePortal',
      version: '2.4.0',
      description: 'Feature-rich CODBSharePoint battle-test portal',
      author: 'CODBSharePoint',
      includeClientSideAssets: true,
      skipFeatureDeployment: false
    });

    addWebPart(ir, {
      name: 'OperationsDashboard',
      displayName: 'Operations Dashboard',
      description: 'Shows KPIs, service alerts, and active work queues',
      framework: 'react'
    });
    addWebPart(ir, {
      name: 'PeopleInsights',
      displayName: 'People Insights',
      description: 'Shows Microsoft Graph powered people and group insights',
      framework: 'react'
    });
    addWebPart(ir, {
      name: 'KnowledgeHub',
      displayName: 'Knowledge Hub',
      description: 'Shows curated guidance, FAQs, and links',
      framework: 'react'
    });

    addGraphPermission(ir, 'User.Read.All');
    addGraphPermission(ir, 'Group.Read.All');
    addGraphPermission(ir, 'Sites.Read.All');

    addColumn(ir, { name: 'Department', displayName: 'Department', type: 'Choice', choices: ['IT', 'HR', 'Finance', 'PublicWorks'] });
    addColumn(ir, { name: 'Priority', displayName: 'Priority', type: 'Choice', choices: ['Low', 'Normal', 'High', 'Critical'] });
    addList(ir, { title: 'Operational Requests', description: 'Tracks internal requests surfaced by the portal', template: 100, fields: ['Department', 'Priority'] });

    addTheme(ir, {
      name: 'CODB Battle Theme',
      primary: {
        themePrimary: '#005a9e',
        themeLighterAlt: '#eff6fc',
        themeLight: '#c7e0f4',
        themeDark: '#004578',
        neutralPrimary: '#323130',
        white: '#ffffff'
      }
    });
    addFormatting(ir, {
      type: 'columnFormatting',
      name: 'PriorityStatus',
      target: 'Priority',
      json: {
        elmType: 'div',
        style: { color: '=if(@currentField == "Critical", "#a4262c", "#323130")' },
        txtContent: '@currentField'
      }
    });
    addProvisioning(ir, {
      type: 'siteScript',
      name: 'BattlePortalSetup',
      description: 'Creates portal dependencies',
      data: { actions: [{ verb: 'createSPList', listName: 'Operational Requests', templateType: 100 }] }
    });
    addPage(ir, {
      name: 'battle-portal.aspx',
      title: 'Battle Portal',
      content: '<h1>Battle Portal</h1><p>Generated by CODBSharePoint.</p>'
    });

    ir.localization.languages = ['es-es'];
    ir.localization.strings = {
      'en-us': { DashboardTitle: 'Operations Dashboard', PeopleTitle: 'People Insights', HubTitle: 'Knowledge Hub' },
      'es-es': { DashboardTitle: 'Panel de Operaciones', PeopleTitle: 'Información de Personas', HubTitle: 'Centro de Conocimiento' }
    };

    const result = await sdk.buildFromIR(ir, battlePortalFiles());

    expect(result.success).toBe(true);
    expect(result.sppkg).toBeDefined();
    expect(validateSPPKGPackage(result.sppkg!)).toEqual([]);
    expect(result.bundle.chunks).toHaveLength(3);
    expect(result.deployment.requiresAdmin).toBe(true);
    expect(result.deployment.permissions.map(permission => permission.permission)).toEqual([
      'User.Read.All',
      'Group.Read.All',
      'Sites.Read.All'
    ]);

    const outputPaths = result.files.map(file => file.path);
    expect(outputPaths).toContain('sharepoint/localization/en-us.resx');
    expect(outputPaths).toContain('sharepoint/localization/es-es.resx');
    expect(outputPaths).toContain('sharepoint/themes/CODB Battle Theme.json');
    expect(outputPaths).toContain('sharepoint/formatting/PriorityStatus.json');
    expect(outputPaths).toContain('sharepoint/provisioning/BattlePortalSetup.json');
    expect(outputPaths).toContain('sharepoint/pages/battle-portal.aspx.json');

    for (const css of result.files.filter(file => file.path.endsWith('.module.css'))) {
      expect(String(css.content)).not.toContain('$');
      expect(String(css.content)).toContain('display: grid');
    }

    const packageFiles = unzipSync(result.sppkg!);
    expect(packageFiles['BattlePortal/OperationsDashboard.bundle.js']).toBeDefined();
    expect(packageFiles['BattlePortal/PeopleInsights.bundle.js']).toBeDefined();
    expect(packageFiles['BattlePortal/KnowledgeHub.bundle.js']).toBeDefined();

    const packageSolution = JSON.parse(strFromU8(packageFiles['BattlePortal/package-solution.json']));
    expect(packageSolution.solution.version).toBe('2.4.0');
    expect(packageSolution.solution.webApiPermissionRequests).toHaveLength(3);

    for (const manifestName of ['OperationsDashboard', 'PeopleInsights', 'KnowledgeHub']) {
      const manifest = JSON.parse(strFromU8(packageFiles[`BattlePortal/${manifestName}.manifest.json`]));
      expect(manifest.loaderConfig.entryModuleId).toBe(`${manifestName}.bundle`);
      expect(manifest.loaderConfig.scriptResources[`${manifestName}.bundle`].path).toBe(`${manifestName}.bundle.js`);
      expect(manifest.loaderConfig.scriptResources.react.version).toBe('18.2.0');
    }

    for (const bundleName of ['OperationsDashboard', 'PeopleInsights', 'KnowledgeHub']) {
      const bundle = strFromU8(packageFiles[`BattlePortal/${bundleName}.bundle.js`]);
      expect(bundle).toContain('define(');
      expect(bundle).not.toContain('Dynamic require');
      expect(bundle).not.toContain('<section');
    }
  });
});

function battlePortalFiles(): Map<string, string> {
  return new Map<string, string>([
    ...webPartFiles('OperationsDashboard', operationsDashboardSource(), dashboardScss()),
    ...webPartFiles('PeopleInsights', peopleInsightsSource(), peopleScss()),
    ...webPartFiles('KnowledgeHub', knowledgeHubSource(), hubScss())
  ]);
}

function webPartFiles(name: string, componentSource: string, scss: string): Array<[string, string]> {
  return [
    [`src/webparts/${name}/${name}WebPart.ts`, webPartSource(name)],
    [`src/webparts/${name}/components/${name}.tsx`, componentSource],
    [`src/webparts/${name}/components/${name}.module.scss`, scss]
  ];
}

function webPartSource(name: string): string {
  return `import * as React from 'react';
import * as ReactDOM from 'react-dom';
import { Version } from '@microsoft/sp-core-library';
import { BaseClientSideWebPart } from '@microsoft/sp-webpart-base';
import ${name} from './components/${name}';

export default class ${name}WebPart extends BaseClientSideWebPart<any> {
  public render(): void {
    const element = React.createElement(${name}, { context: this.context, siteUrl: this.context.pageContext.web.absoluteUrl });
    ReactDOM.render(element, this.domElement);
  }

  protected onDispose(): void {
    ReactDOM.unmountComponentAtNode(this.domElement);
  }

  protected get dataVersion(): Version {
    return Version.parse('1.0');
  }
}
`;
}

function operationsDashboardSource(): string {
  return `import * as React from 'react';
import styles from './OperationsDashboard.module.scss';

const metrics = [
  { label: 'Open Requests', value: 42, trend: '+8%' },
  { label: 'Critical Items', value: 6, trend: '-2%' },
  { label: 'Resolved Today', value: 17, trend: '+14%' }
];

export default class OperationsDashboard extends React.Component<any, any> {
  public render(): React.ReactElement<any> {
    return <section className={styles.shell}>
      <h2>Operations Dashboard</h2>
      <div className={styles.metrics}>{metrics.map(metric => <article className={styles.card} key={metric.label}>
        <strong>{metric.value}</strong><span>{metric.label}</span><small>{metric.trend}</small>
      </article>)}</div>
      <div className={styles.alert}>Critical service queue requires review.</div>
    </section>;
  }
}
`;
}

function peopleInsightsSource(): string {
  return `import * as React from 'react';
import styles from './PeopleInsights.module.scss';

export default class PeopleInsights extends React.Component<any, any> {
  public state = { people: [{ displayName: 'Ada Lovelace', department: 'IT' }, { displayName: 'Grace Hopper', department: 'Finance' }] };

  public async componentDidMount(): Promise<void> {
    const factory = this.props.context?.msGraphClientFactory;
    if (!factory) return;
    const client = await factory.getClient('3');
    await client.api('/users').version('v1.0').select('displayName,department,mail').top(5).get();
    await client.api('/groups').version('v1.0').select('displayName,mail').top(5).get();
    await client.api('/sites/root').version('v1.0').get();
  }

  public render(): React.ReactElement<any> {
    return <section className={styles.panel}>
      <h2>People Insights</h2>
      <div className={styles.people}>{this.state.people.map((person: any) => <div className={styles.person} key={person.displayName}>
        <span>{person.displayName}</span><small>{person.department}</small>
      </div>)}</div>
    </section>;
  }
}
`;
}

function knowledgeHubSource(): string {
  return `import * as React from 'react';
import styles from './KnowledgeHub.module.scss';

const articles = [
  { title: 'Emergency Operations', tag: 'Critical' },
  { title: 'Permit Processing', tag: 'Workflow' },
  { title: 'Public Records', tag: 'Reference' }
];

export default class KnowledgeHub extends React.Component<any, any> {
  public render(): React.ReactElement<any> {
    return <section className={styles.hub}>
      <h2>Knowledge Hub</h2>
      <div className={styles.search}>Search policies, procedures, and FAQs</div>
      <div className={styles.articles}>{articles.map(article => <article className={styles.article} key={article.title}>
        <strong>{article.title}</strong><span>{article.tag}</span>
      </article>)}</div>
    </section>;
  }
}
`;
}

function dashboardScss(): string {
  return `$primary: #005a9e;
$danger: #a4262c;

.shell {
  display: grid;
  gap: 16px;

  .metrics {
    display: grid;
    grid-template-columns: repeat(3, minmax(0, 1fr));
    gap: 12px;
  }

  .card {
    border-top: 4px solid $primary;
    box-shadow: 0 2px 8px rgba(0, 0, 0, 0.12);
    padding: 16px;
  }

  .alert {
    border-left: 4px solid $danger;
    padding: 12px;
  }
}
`;
}

function peopleScss(): string {
  return `$accent: #107c10;

.panel {
  display: grid;
  gap: 12px;

  .people {
    display: grid;
    grid-template-columns: repeat(2, minmax(0, 1fr));
    gap: 10px;
  }

  .person {
    border-left: 3px solid $accent;
    padding: 10px;
  }
}
`;
}

function hubScss(): string {
  return `$surface: #faf9f8;

.hub {
  display: grid;
  gap: 14px;

  .search {
    background: $surface;
    border-radius: 20px;
    padding: 10px 16px;
  }

  .articles {
    display: grid;
    grid-template-columns: repeat(3, minmax(0, 1fr));
    gap: 12px;
  }

  .article {
    border: 1px solid #edebe9;
    padding: 14px;
  }
}
`;
}
